import getpass
import telnetlib

HOST = "192.168.238.150" 
user = input("Enter your remote account: ") 
password = getpass.getpass() 

tn = telnetlib.Telnet(HOST) 

tn.read_until(b"Username: ") 
tn.write(user.encode('ascii') + b"\n") 
if password: 
    tn.read_until(b"Password: ") 
    tn.write(password.encode('ascii') + b"\n") 

tn.write(b"enable\n")  
tn.write(b"loopedback\n") 
tn.write(b"conf t\n") 
tn.write(b"ip routing\n") 
tn.write(b"int lo0\n") 
tn.write(b"ip add 1.1.1.150 255.255.255.255\n")
tn.write(b"int vlan 10\n")
tn.write(b"description IT VLAN\n") 
tn.write(b"ip add 192.168.10.150 255.255.255.0\n")
tn.write(b"no shut\n") 
tn.write(b"int gi3/1\n")
tn.write(b"switchport mode access\n")
tn.write(b"switchport access vlan 10\n")
tn.write(b"no shut\n")
tn.write(b"int vlan 20\n")
tn.write(b"description Engineering VLAN\n")
tn.write(b"ip add 192.168.20.150 255.255.255.0\n")
tn.write(b"no shut\n") 
tn.write(b"int gi3/2\n")
tn.write(b"switchport mode access\n")
tn.write(b"switchport access vlan 20\n")
tn.write(b"no shut\n")
tn.write(b"int vlan 30\n")
tn.write(b"description Sales VLAN\n")
tn.write(b"ip add 192.168.20.150 255.255.255.0\n")
tn.write(b"no shut\n")
tn.write(b"int gi3/3\n")
tn.write(b"switchport mode access\n")
tn.write(b"switchport access vlan 30\n")
tn.write(b"no shut\n")
tn.write(b"int ra gi1/0 - 2\n")
tn.write(b"switchport trunk encap dot\n")
tn.write(b"switchport mode trunk\n")
tn.write(b"channel-group 5 mode desirable\n")
tn.write(b"int vlan 1\n")
tn.write(b"standby 5 ip 192.168.238.5\n")
tn.write(b"router ospf 1\n")
tn.write(b"network 0.0.0.0 0.0.0.0 area 0\n") 
tn.write(b"router-id 1.1.1.1\n")
tn.write(b"end\n")
tn.write(b"wr\n") 
tn.write(b"exit\n")

print(tn.read_all().decode('ascii')) 